# Generated by Django 2.2 on 2020-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dguys', '0005_auto_20200209_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dguy',
            name='location',
            field=models.CharField(choices=[('Farmgate', 'Farmgate'), ('Dhanmondi', 'Dhanmondi'), ('Wari', 'Wari'), ('Moghbazar', 'Moghbazar'), ('Badda', 'Badda'), ('Mohammadpur', 'Mohammadpur'), ('Uttara', 'Uttara'), ('Malibag', 'Malibag'), ('Khilgaon', 'Khilgaon'), ('Dhaka Cantonment', 'Dhaka Cantonment'), ('Jatrabari', 'Jatrabari'), ('Mouchak', 'Mouchak')], default='Farmgate', max_length=200),
        ),
    ]
